name: pdf_checker
description: Use to check permission and security of pdf file.
version: 1.1.0
platforms:
  android:
  ios:

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ideal.pdf_checker
        pluginClass: PdfCheckerPlugin
      ios:
        pluginClass: PdfCheckerPlugin